name: CI

# Trigger the workflow on push or pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - uses: actions/checkout@v3  # Checkout the repository content

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Specify Zulu as the JDK distribution
          java-version: 8

      - name: Build with Maven
        run: mvn clean package  # Run Maven to build the application

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: verademo.war
          path: target/verademo.war
